#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --distribution bookworm \
    --parent-distribution bookworm \
    --parent-debian-installer-distribution bookworm \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    --mirror-chroot-security "http://security.debian.org/debian-security/" \
    --mirror-binary "http://deb.debian.org/debian/" \
    --mirror-binary-security "http://security.debian.org/debian-security/" \
    --parent-mirror-bootstrap "http://deb.debian.org/debian/" \
    --parent-mirror-chroot "http://deb.debian.org/debian/" \
    --parent-mirror-chroot-security "http://security.debian.org/debian-security/" \
    --parent-mirror-binary "http://deb.debian.org/debian/" \
    --parent-mirror-binary-security "http://security.debian.org/debian-security/" \
    --architectures amd64 \
    --archive-areas "main contrib non-free-firmware" \
    --linux-flavours amd64 \
    --bootloader syslinux \
    --binary-images iso-hybrid \
    --iso-application "VEILOS Operating System" \
    --iso-preparer "VEILOS Project Team" \
    --iso-publisher "VEILOS Core Team" \
    --iso-volume "VEILOS_LIVE" \
    --memtest none \
    --win32-loader false \
    --apt-recommends false \
    --apt-secure true \
    --security true \
    --backports false \
    --bootappend-live "boot=live components quiet splash hostname=VEILOS username=veilos live-config.timezone=Etc/UTC live-config.locales=en_US.UTF-8 live-config.keyboard-layouts=us noautomount" \
    "${@}"