#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --distribution bookworm \
    --architectures amd64 \
    --archive-areas "main contrib non-free-firmware" \
    --linux-flavours amd64 \
    --bootloader syslinux,grub-efi \
    --binary-images iso-hybrid \
    --image-name "veilos-live-amd64" \
    --iso-application "VEILOS Operating System" \
    --iso-preparer "VEILOS Project Team" \
    --iso-publisher "VEILOS Core Team" \
    --iso-volume "VEILOS_LIVE" \
    --memtest none \
    --win32-loader false \
    --apt-recommends false \
    --apt-secure true \
    --security true \
    --updates true \
    --backports false \
    --bootappend-live "boot=live components quiet splash hostname=VEILOS username=veilos live-config.timezone=Etc/UTC live-config.locales=en_US.UTF-8 live-config.keyboard-layouts=us noautomount" \
    "${@}"